import { Poppins } from "next/font/google";
import { AppProvider } from "@/components/AppContext";
import "./globals.css";
import Header from "../components/layout/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "BOBA 2 GO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-boba-bg bg-fixed">
      <body className={poppins.className}>
        <main className="max-w-5xl mx-auto p-12 bg-white min-h-screen">
          <AppProvider>
            <Header />
            {children}
            <footer className="border-t p-8 text-center mt-16 text-secondary-1">
              &copy; 2023 All Rights Reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
